### ISSUE TITLE
CocoaPods could not find compatible versions for pod "gRPC-Core":

### ISSUE THREAD

**Issue by dangell7** [xpring-eng/XpringKit#55] opened 2019-12-26 22:42 UTC
I'm working on my fork and I use swift 5 with Google Firestore Dependencies. I'm now running into the issue using `pod install` with the following errors: 

```
[!] CocoaPods could not find compatible versions for pod "gRPC-Core":
  In snapshot (Podfile.lock):
    gRPC-Core (= 1.21.0)

  In Podfile:
    Firebase/Firestore was resolved to 6.14.0, which depends on
      FirebaseFirestore (~> 1.8.2) was resolved to 1.8.3, which depends on
        gRPC-C++ (= 0.0.9) was resolved to 0.0.9, which depends on
          gRPC-C++/Implementation (= 0.0.9) was resolved to 0.0.9, which depends on
            gRPC-Core (= 1.21.0)

    XpringKit (from `/Users/denisangell/projects/xrp/xpringKit/XpringKit.podspec`) was resolved to 1.2.1, which depends on
      SwiftGRPC was resolved to 0.4.3, which depends on
        gRPC-Core (~> 1.11.0)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `gRPC-Core` inside your development pod `XpringKit`.
   You should run `pod update gRPC-Core` to apply changes you've made.
```
I believe this is a dependency issue... So I went https://github.com/grpc/grpc-swift and found a depreciation issue?
```
‼️ Please use the nio branch ‼️
gRPC Swift versions v0.x based on gRPC-Core will soon be replaced with a re-implementation based on SwiftNIO.

We strongly suggest that new projects use the re-implementation from the nio branch which we consider to be production ready.

Please see DEPRECATION.md for more information.
```

My goal is to get all of this up to swift 5. 

Happy Hollidays!!

**Comment by dangell7** [comment] 2019-12-26 23:20
My podFile was attempting to install on 11.3 where everything else in the project was 13.2.

**Comment by dangell7** [comment] 2019-12-26 23:21
Sorry for all the confusion.. Still Learning

**Comment by sidstew** [comment] 2020-03-26 21:06
Hey @dangell7  - I am pretty new to this too and am getting this error as well. What did you do to resolve it? Any help would be appreciated!

Thanks!

**Comment by dangell7** [comment] 2020-03-26 22:20
Can you post the stack trace?

**Comment by dangell7** [comment] 2020-03-26 22:21
I had to lock in grpc with a separate repo

**Comment by sidstew** [comment] 2020-03-26 23:29
This is what i get when i try to pod install within my project in my terminal:

> [!] CocoaPods could not find compatible versions for pod "gRPC-Core":
>   In snapshot (Podfile.lock):
>     gRPC-Core (= 1.21.0)
> 
>   In Podfile:
>     Firebase/Firestore was resolved to 6.14.0, which depends on
>       FirebaseFirestore (~> 1.8.2) was resolved to 1.8.3, which depends on
>         gRPC-C++ (= 0.0.9) was resolved to 0.0.9, which depends on
>           gRPC-C++/Implementation (= 0.0.9) was resolved to 0.0.9, which depends on
>             gRPC-Core (= 1.21.0)
> 
>     XpringKit was resolved to 1.1.3, which depends on
>       SwiftGRPC was resolved to 0.4.3, which depends on
>         gRPC-Core (~> 1.11.0)

My Podfile consisits of:
 pod 'MBProgressHUD'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Email'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Protobuf'
pod 'XpringKit'

Is that what you were asking for? I apologize, this is pretty new to me. I have been reading through some gRPC documentation you provided above and have successfully completed the basic tutorial. Still trying to read more about it though. Thanks for the help I truly appreciate it!

**Comment by dangell7** [comment] 2020-03-27 02:08
Yeah thats it. @keefertaylor How do you want to handle this? I forked both this repo and the grpc swift and held the grpc repo it to the specific version of grpc [here](https://github.com/dangell7/grpc-swift/commit/1e2a97f2c7d318d2ab155f97c9c07d0e71d1a0ff) and again [here](https://github.com/dangell7/grpc-swift/commit/72b2b2e56ace863b4d17b6048244fb50592f0d65). Then I changed this repo to use `XGRPC-Swift` the repo fork I created.

**Comment by dangell7** [comment] 2020-03-27 02:11
@sidstew whatcha building if you dont mind me asking?

**Comment by keefertaylor** [comment] 2020-03-27 07:45
Hey folks, 

Looking at the output here: 
```
[!] CocoaPods could not find compatible versions for pod "gRPC-Core":
In snapshot (Podfile.lock):
gRPC-Core (= 1.21.0)

In Podfile:
Firebase/Firestore was resolved to 6.14.0, which depends on
FirebaseFirestore (~> 1.8.2) was resolved to 1.8.3, which depends on
gRPC-C++ (= 0.0.9) was resolved to 0.0.9, which depends on
gRPC-C++/Implementation (= 0.0.9) was resolved to 0.0.9, which depends on
gRPC-Core (= 1.21.0)

XpringKit was resolved to 1.1.3, which depends on
  SwiftGRPC was resolved to 0.4.3, which depends on
    gRPC-Core (~> 1.11.0)
```

The problem is that:
1) You're depending on `Firebase/Firestore` (`v6.14.0`) which transitively depends on `gRPC-Core v1.2.0`
2) You're also depending on `XpringKit` (`v.1.1.13`) which transitively depends on `gRPC-Core v1.11.0`
3) You can't bundle both `gRPC-Core v1.2.0` and `gRPC-Core v1.11.0` (you can't add the same framework at different versions to a single binary)

I've opened #172 to upgrade our dependencies and also lock them. Unfortunately, this has the result of wanting to bundle `gRPC-Core v1.23.0` which is still going to be incompatible with your FireStore dependency. 

Ultimately, you're going to need to find a way to get your dependency versions to agree with each other in order to get building. I'm happy to upgrade anything in XpringKit, but not downgrade (unless you can prove that there's an extenuating circumstance). 

A few notes:
- It looks like you are using an out of date version of both XpringKit. The [latest version of XpringKit](https://cocoapods.org/pods/xpringkit) is 2.0.0 and you're depending on 1.1.3. You probably want to pull the latest code :)  
- Also looks like you're using an out of date version of Firebase/Firestore. [latest is 6.21.0](http://cocoapods.org/pods/firebase) and you are installing 6.14.0. 
- I'm surprised you're pulling old versions since you haven't specified versions in your `Podfile`. You may want to try running `pod repo update` to refresh your CocoaPods repository on your machine and then run `pod install` again.
- You can control the dependencies you bring in. By default you're not specifying dependency versions in your `Podfile`, which you probably want to do. 

From the [CocoaPods Documentation](https://guides.cocoapods.org/syntax/podspec.html#dependency): 
> Dependencies can specify versions requirements. The use of the optimistic version indicator ~> is recommended because it provides good control over the version without being too restrictive. For example, ~> 1.0.1 is equivalent to >= 1.0.1 combined with < 1.1. Similarly, ~> 1.0 will match 1.0, 1.0.1, 1.1, but will not upgrade to 2.0.

I'd try at least updating to the latest version of each library and figuring out if they place nicely with each other. Note that #155 won't be pulled into the build until it is merged and a new release is cut. I plan to cut a 3.0.0. release after that lands. 

----

> Yeah thats it. @keefertaylor How do you want to handle this? I forked both this repo and the grpc swift and held the grpc repo it to the specific version of grpc [here](https://github.com/dangell7/grpc-swift/commit/1e2a97f2c7d318d2ab155f97c9c07d0e71d1a0ff) and again [here](https://github.com/dangell7/grpc-swift/commit/72b2b2e56ace863b4d17b6048244fb50592f0d65). 

These commits 404 for me. Is it a private repo?

**Comment by keefertaylor** [comment] 2020-03-27 09:45
If you're interested in following the upgrade, #172 contains the updated libraries and #173 cuts the associated release.

**Comment by sidstew** [comment] 2020-03-27 13:51
@keefertaylor and @dangell7  thank you so much for this information! This is super helpful. I will see what I can do and will followup on this thread. 
@dangell7 I'm building an iOS app that is a P2P kind of app used for educational purposes. Mostly a platform where students can post questions and tip people in XRP who assist them.

**Comment by sidstew** [comment] 2020-03-27 16:15
Ok so here is what I did and it allowed me to install XpringKit!
1. Did a 'sudo gem install cocoapods' to update cocoapods
2. Updated my XpringKit pod to XpringKit,'~> 2.0'
3. Tried pod install but got this error below. To resolve the issue I basically just updated my deployment target in my podfile.
> [!] CocoaPods could not find compatible versions for pod "XpringKit":
>   In Podfile:
>     XpringKit (~> 2.0)
> 
> Specs satisfying the `XpringKit (~> 2.0)` dependency were found, but they required a higher minimum deployment target.

4. ran **pod update 'Firebase/Firestore'** in terminal - this seemed to successfully install XrpingKit for me. 

> Updating local specs repositories
> 
> CocoaPods 1.9.1 is available.
> To update use: `sudo gem install cocoapods`
> 
> For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.9.1
> 
> Analyzing dependencies
> Downloading dependencies
> Installing BigInt (5.0.0)
> Installing Firebase 6.1.0 (was 6.14.0)
> Installing FirebaseAnalytics 6.0.1 (was 6.1.7 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
> Installing FirebaseAuth 6.1.2 (was 6.4.1 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
> Installing FirebaseAuthInterop 1.1.0 (was 1.0.0 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
> Installing FirebaseCore 6.0.1 (was 6.5.0 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
> Installing FirebaseFirestore 1.3.1 (was 1.8.3 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
> Installing FirebaseInstanceID 4.2.7 (was 4.2.8 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
> Installing FirebaseStorage 3.2.1 (was 3.4.3 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
> Installing GoogleAppMeasurement 6.0.1 (was 6.1.7 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
> Installing SwiftGRPC (0.9.1)
> Installing SwiftProtobuf (1.5.0)
> Installing XpringKit (2.0.0)
> Installing gRPC-C++ 0.0.8 (was 0.0.9 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
> Installing gRPC-Core 1.19.0 (was 1.21.0 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
> Removing FirebaseCoreDiagnostics
> Removing FirebaseCoreDiagnosticsInterop
> Removing GoogleDataTransport
> Removing GoogleDataTransportCCTSupport
> Removing abseil
> Generating Pods project
> Integrating client project
> Pod installation complete! There are 12 dependencies from the Podfile and 28 total pods installed.

**Closed** 2020-04-07 16:43 UTC
